### ISSUE TITLE
Not starting using terminology under arch linux

### ISSUE THREAD

**Issue by CodingJonas** [LazoCoder/Pokemon-Terminal#101]
This project is amazing, and I would love to work with it. Unfortunately I can't make it work.
I installed Terminology and then the `pokemon-terminal` via the arch repository.

When I first run it I got the error message
```
$ pokemon mew       
This terminal emulator is not supported.
```
I looked into the source code and saw you are checking environment variables.
After setting `TERMINOLOGY` to `1` I get a new error message, but I couldn't find a way to fix it:
```
$ pokemon mew       
}bt/home/jonas/gitDownload/Pokemon-Terminal/Images/Generation I - Kanto/151.jpg%  
```
I have the latest arch linux version and terminology is also up to date. I use the i3 window manager and the zsh, in case some of that is important.

**Comment by charlesmilette** [comment]
It seems you aren't running the command via the terminology terminal emulator.

It should be available if you run the `terminology` command to spawn it and then run your commands in it.

**Comment by CodingJonas** [comment]
You are right. I thought the program will spawn a new terminal. Running it from the terminology window works just fine!
