### ISSUE TITLE
script error: Expected end of line but found identifier. (-2741)

### ISSUE THREAD

**Issue by poush** [LazoCoder/Pokemon-Terminal#102]
Hwy, Actually I was trying the pokemon terminal for the first time and I encountered with a issue on first run.

The error says 
```
/usr/local/lib/node_modules/pokemon-terminal/./Scripts/background.scpt:39:46: script error: Expected end of line but found identifier. (-2741)
```

OS: macOS 10.12 Sierra 
Python: 3.5.1
Terminal: iTerm2 3.0.15 
Installation type: npm

Command tried: pokemon pikachu

**Comment by LazoCoder** [comment]
As per the header "Solutions for Common Issues" in the readme:

> If you get the error: 39:46: syntax error: Expected end of line but found identifier. (-2741). Locate the file ITerm.py in adapter/implementations and on line 7, change "iTerm" to "iTerm2". If you still experience the error, try changing it to "iTerm 2".

If the solution doesn't work for you, you may re-open the ticket.
