### ISSUE TITLE
Support for Konsole

### ISSUE THREAD

**Issue by samr28** [LazoCoder/Pokemon-Terminal#107]
Are there any plans to add support for Konsole? It should be possible from what I can see (see screenshot below). 
![image](https://user-images.githubusercontent.com/3688992/29744158-cdf3f598-8a64-11e7-814d-21c8114e61fc.png)

**Comment by LazoCoder** [comment]
There are a lot of terminals that allow a user to change the background image through the GUI but there is no way to do it via command line. If Konsole had a command to change the background, this would be easy to implement, but a quick google search reveals that it does not.
