### ISSUE TITLE
Error when installing on Arch Linux using the AUR

### ISSUE THREAD

**Issue by ThePotatoGod99** [LazoCoder/Pokemon-Terminal#108]
> Traceback (most recent call last):
  File "/usr/bin/pokemon", line 9, in <module>
    from pokemonterminal import scripter
ModuleNotFoundError: No module named 'pokemonterminal'

**Comment by sylveon** [comment]
I did the AUR package, and they recently made changes to how it is packaged. Thanks for letting me know, expect an update in a few days.

**Comment by sylveon** [comment]
Updated. Lemme know if it doesn't works.

**Comment by ThePotatoGod99** [comment]
I managed to download the package using yaourt. No errors.

I can run it, but since I don't use Tilix or terminology, I get 'this terminal emulator is not supported'

I'm currently working on making it compatible with xfce4-terminal. I'll do a pull request when it's completed :)
