### ISSUE TITLE
Terminology: 'This terminal emulator is not supported.'

### ISSUE THREAD

**Issue by GISerDaiShaoqing** [LazoCoder/Pokemon-Terminal#111]
I have installed the laterest Terminology, but the screen showed 'This terminal emulator is not supported.' Why?Could you help me. Thank you very much.

**Comment by sylveon** [comment]
You need to run this command in the actual Terminology terminal
emulator, not your preferred one. There should be an entry in your app
list or you can manually invoke it with the "terminology" command.

-- 
Envoyé de mon Gmail

**Comment by GISerDaiShaoqing** [comment]
@sylveon 
I have run this command in the actual Terminology terminal emulator. And when I type 'pokemon _pikachu', the screen showed 'TypeError: argument of type 'NoneType' is not iterable'.

**Comment by sylveon** [comment]
That a bug in the code. cc @LazoCoder

**Comment by GISerDaiShaoqing** [comment]
I use Tilix successfully. Reference: https://www.maketecheasier.com/customize-linux-terminal-pokemon-skins/. Thanks a lot.
