### ISSUE TITLE
Add customizable default pokemon theme config

### ISSUE THREAD

**Issue by minghu6** [LazoCoder/Pokemon-Terminal#115]
I want to open a terminal with the specific pokemon theme, don't need to use `pokemon xxx` every time.
Just like a pokemon following you. 

Maybe we can just depend on `r/w` a .ini file, json file or other readble config file.
If you think it's a good idea, I will supply a pr for the issue.

**Comment by sylveon** [comment]
how to make it persist is written straight in the readme

**Comment by minghu6** [comment]
I mean **specific** not random pokemon.
It's difficult to recognize the character in some backgound color to be honest 
and I have favourite pokemon :)

**Comment by sylveon** [comment]
Instead of adding `pokemon random` to your bashrc, add `pokemon <name>`

`echo "pokemon sylveon" >> ~/.bashrc` for example

**Comment by minghu6** [comment]
ok.
