### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by nkrebs13** [LazoCoder/Pokemon-Terminal#12]
Hi - can you please update the readme with your color setup? You went over the transparency/blurring, but how it looks is highly dependent on your colors.

Maybe export your colors and put them in the repository?

**Comment by LazoCoder** [comment]
Is the problem that your colors look darker than mine?
Try changing your blending setting to max. To do this go to the same window that contains the transparency and blur settings (the same window as the screenshot under the Suggestions section in the readme) and you will see a setting for blending on the right side. Set it to max and it should brighten up the colors.
Let me know if this fixes the issue for you. If it does, I should probably add it to the readme to make it more clear for others.

**Comment by LazoCoder** [comment]
See #5 under the Suggestions section.

**Comment by salman-bhai** [comment]
Is this Issue resolved?

**Comment by LazoCoder** [comment]
@salman-bhai are you also having color issues? Did the the blending fix not work for you? Can you post an image so that I can see what the issue is?

**Comment by nkrebs13** [comment]
I'm not sure what happened - the colors on my terminal completely disappeared. The text was only white. I didn't change my iTerm2 theme or anything. 

In any case - I deleted iTerm2,  ran `defaults delete com.googlecode.iterm2` to delete the saved profiles, and re-installed iTerm2 and it works now
