### ISSUE TITLE
Syntax error while running

### ISSUE THREAD

**Issue by pukseli** [LazoCoder/Pokemon-Terminal#124]
Hi!
when running the software i got error

> username@arvaja-VirtualBox:~/git$ pokemon
> Traceback (most recent call last):
>   File "/home/username/.Pokemon-Terminal/pokemon", line 5, in <module>
>     from pokemonterminal.main import main
>   File "/home/username/.Pokemon-Terminal/pokemonterminal/main.py", line 36
>     print(f"Starting slideshow with {len(filtered)}, pokemon " +
 > ^ (this should be on " char)
> SyntaxError: invalid syntax

my python version:

> $ python -V
> Python 3.6.3
> 

And i run ubuntu 16.04

**Comment by cclauss** [comment]
Try: python3 pokemon

**Comment by LazoCoder** [comment]
I get this error also when I use Python 2.7 and Python 3.5 but it works with Python 3.6.

@pukseli probably has multiple versions of Python installed and Pokemon Terminal is using the one that is not Python 3.6.

Is there a way we can fix this so it always runs with Python 3.6? The first line in main.py is:
> #!/usr/bin/env python3

Maybe it would fix the issue if we changed that to
> #!/usr/bin/env python3.6

**Comment by samosaara** [comment]
Sure, AFAIK every distro installs a alias like that. Most importantly, the mainstream end-user ones does and i bet an arch or Slackware user knows how to fix a shebang comment

**Comment by cclauss** [comment]
Why force the user to fix our code?  Let's fix it out of the box.

**Comment by samosaara** [comment]
@cclauss Oh no, not what I meant, I was considering some crazy ass strange distro that might not have the python 3.6 alias. But actually that's very far-fetch of me, just NVM.

**Comment by pukseli** [comment]
still if i write just pokemon, i got the same error.
When running "python3.6 pokemon"  I got  "This terminal emulator is not supported." error instead

**Comment by sylveon** [comment]
The first problem should be fixed by pulling the latest commit (`git pull`)

The other one is fixed by using either Tilix, Terminology or iTerm2 as terminal emulator instead of the one you are using, as they are the only ones supported right now.
