### ISSUE TITLE
`TypeError: main() missing 1 required positional argument: 'argv'` on Arch Linux

### ISSUE THREAD

**Issue by sylveon** [LazoCoder/Pokemon-Terminal#127]
```sh
$ pokemon 700
Traceback (most recent call last):
  File "/usr/bin/pokemon", line 11, in <module>
    load_entry_point('pokemon-terminal==1.1.0', 'console_scripts', 'pokemon')()
TypeError: main() missing 1 required positional argument: 'argv'
```

Python version 3.6.3, running Pokemon-Terminal with commit f1db84d

**Comment by samosaara** [comment]
I'm not being able to reproduce here in arch linux, python 3.6.3 how did you install it? Because that path of the executable seems a little off.

**Comment by sylveon** [comment]
This is a system-wide pip install. The `pokemon` executable has the following contents:

```py
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pokemon-terminal==1.1.0','console_scripts','pokemon'
__requires__ = 'pokemon-terminal==1.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pokemon-terminal==1.1.0', 'console_scripts', 'pokemon')()
    )
```

**Comment by cclauss** [comment]
* #!/usr/bin/python  # is going to hardcode you into a single version of Python (probably Python 2) in a given directory
* #!/usr/bin/env python  # will allow you to find the first version of Python (probably Python 2) on $PATH
* #!/usr/bin/env python  # will allow you to find the first version of Python 3 on $PATH

Give that this codebase need Python 3.6, I would believe that the last shebang line is best.

I would also recommend that you do: __python3 -m pip install...__
