### ISSUE TITLE
Implementing the adapter pattern to the wallpaper providers

### ISSUE THREAD

**Issue by samosaara** [LazoCoder/Pokemon-Terminal#129]
So I finally want to do this, but I want every one to be on the same page not to have to redo lots of stuff after, and I also need to some help on how the f. Mac OS wallpaper setting works. This first message will be updated as feedback

So My initial plan is this folder structure:
```text
pokemonterminal/wallpaper
├── gnome.py
├── __init__.py
├── darwin.py
└── wallpaper_provider.py
```
and `__init__.py` would have the helper functions such as `getCurrentProvider` that would return `None` on unsupported, also it would re-export the other modules. `wallpaper_provider.py` would have the 'interface' for the others providers to implement and I was simply thinking a single method called change wallpaper that doesn't return anything but may throw an error if anything goes wrong.

Now as some of you have noticed gnome isn't an operating system codename as darwin, but since mac os DE isn't interchangeable as linux I thought i would just call the D.E same as the system codename. 

Now, I know how changing the wallpaper of gnome works, I was the one who made the current wallpaper changing spaghetti, but just to clarify, in mac you have to save to a .osa script and then call it? There isn't a command to do that? And can't we pipe the osa script from stdin into the interpreter? e.g.: 
```bash
echo "osa script; set wallpapper=pokemon/10.jpg" | osa-scirpt-reader
```

**Comment by cclauss** [comment]
A requirement that I would be interested to see is that adapters be self loading and and self contained.  Contributors only need to edit one file when contributing a new adapter.

This would mean that adapters would operate like plugins in the sense that all you need to do is put an adapter into the adapter and it would be usable the next time the app is run.  I did some hacking around on this idea at https://github.com/cclauss/adapter_pattern  The approach is that the [AdapterInterface looks in its own directory and autoloads all adapters that are proper subclasses of itself](https://github.com/cclauss/adapter_pattern/blob/master/adapters/AdapterInterface.py#L23).

**Comment by samosaara** [comment]
Discussion moved to #130
