### ISSUE TITLE
Remove Selected Pokemon

### ISSUE THREAD

**Issue by adrum** [LazoCoder/Pokemon-Terminal#13]
Is there a command to remove the theme? I know you can just open a new shell, but I didn't know if it was possible to have a way to set the selected pokemon to none.

**Comment by LazoCoder** [comment]
There is no way to do this at the moment. Its a good idea though, I'll see if I can find the time to add this.

**Comment by LazoCoder** [comment]
You can now use *pokemon clear* to remove the current pokemon.
