### ISSUE TITLE
Celebration! 🎉

### ISSUE THREAD

**Issue by LazoCoder** [LazoCoder/Pokemon-Terminal#133]
My friend Riba Linux posted a YouTube video on Pokemon Terminal today:
https://www.youtube.com/watch?v=CWy4kn4Iwhc

🎉🎉🎉

I wanted to say thanks to the team for helping create and maintain Pokemon Terminal :)

If you have contributed to this project feel free to put it on your résumé.

Also make sure you share the video with your friends!

😀

**Comment by samosaara** [comment]
The message only last message I forgot to fix and left behind to fix last will now haunt me forever :rofl: https://github.com/LazoCoder/Pokemon-Terminal/commit/a089e47adc7f9749e0b3bcff915ab2d0ab46bf57#diff-e7293824bedd00bff712f201139330ebR96

**Comment by LazoCoder** [comment]
LOL its ok
