### ISSUE TITLE
Tilix TypeError

### ISSUE THREAD

**Issue by goldug** [LazoCoder/Pokemon-Terminal#139]
Hey.
I tried Pokemon-Terminal in Terminology and it worked, but not so great (Terminology's fault), so I tried it with Tilix instead. This did not work.
I get this error:
`$ pokemon
Traceback (most recent call last):
  File "/usr/local/bin/pokemon", line 8, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pokemonterminal/main.py", line 135, in main
    scripter.change_terminal(target.get_path())
  File "/usr/local/lib/python3.6/dist-packages/pokemonterminal/scripter.py", line 81, in change_terminal
    TERMINAL_PROVIDER.change_terminal(image_file_path)
TypeError: change_terminal() missing 1 required positional argument: 'path'
`
I've tried to fix it myself, but I don't know enough python to locate the issue, and google didn't solve it for me either.
So something must've happened so that Tilix won't cooperate with the script anymore.
I'm running Ubuntu 18.10 (tried with 17.10 first, same problem, so I upgraded), Tilix is v1.7.1.
I have python 3.6. But since it works with Terminology, I don't think it's something my OS is missing.

**Comment by sylveon** [comment]
Thanks, I've made a mistake when refactoring it around, it should be fixed if you update.
