### ISSUE TITLE
Not loading images

### ISSUE THREAD

**Issue by Shaelmaar** [LazoCoder/Pokemon-Terminal#141]
After doing a fresh install on macOS 10.13.2 via `pip3.6 install --user git+https://github.com/LazoCoder/Pokemon-Terminal.git`
I receive the following error message when trying to run the script:

[error.txt](https://github.com/LazoCoder/Pokemon-Terminal/files/1684595/error.txt)

**Comment by sylveon** [comment]
When was your clean install? This issue was fixed 12 days ago by 9d3687561619c72aaf5488be2c38780042130fbf

**Comment by Shaelmaar** [comment]
It seems not deleting the old version first (I thought it would just be overridden) caused my problem.  It's working fine now
