### ISSUE TITLE
Python 3.6?

### ISSUE THREAD

**Issue by pjrulez** [LazoCoder/Pokemon-Terminal#142]
I'm using Debian Stretch, which has Python 2.7.13 and 3.5.3 installed.
3.6 is not available and trying to install backports version throws a warning configuration may break other packages in Stretch. I'm not ready to delve into unstable or experimental waters...

Is it possible to compile a package which can be installed with earlier versions of Pythos for my Pokemon pleasures?

**Comment by LazoCoder** [comment]
The older version uses Python 3.5. It has just about everything that the newer one has with the exception of some minor differences.

See: https://github.com/LazoCoder/Pokemon-Terminal/tree/8085a415d8c9b46c127ee6704c1b7afe59c9cada

**Comment by jimmyorourke** [comment]
Alternatively install python3.6 backports for debian stretch to get all the great python3.6 stuff 😄 
https://github.com/chriskuehl/python3.6-debian-stretch
I've installed these on a few systems without issue
