### ISSUE TITLE
pokemon-font

### ISSUE THREAD

**Issue by Superpencil** [LazoCoder/Pokemon-Terminal#145]
👋🏻 @LazoCoder Perhaps a fun idea to bundle https://superpencil.com/work/pokemon-font/ ?

**Comment by samosaara** [comment]
But how? A option to also change the font of the terminal?

**Comment by LazoCoder** [comment]
That's neat. We are trying to avoid [feature creep](https://en.wikipedia.org/wiki/Feature_creep) at the moment, otherwise this would have been a nice addition. Either way, thanks for sharing.
