### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by anushavasudev** [LazoCoder/Pokemon-Terminal#15]
.Pokemon-Terminal/./Scripts/background.scpt:39:46: script error: Expected end of line but found identifier. (-2741)

That's the error when I do: pokemon [*****]

**Comment by tommcgurl** [comment]
@anushavasudev So I was facing the same issue. Turns out the `scripter.py` was generating a `background.scpt` file containing the command `tell application "iTerm"` when in fact my OS knows iterm2 as "iTerm 2".

To fix this you can edit the following line in the function `__terminal_script` in  `.Pokemon-Terminal/scripter.py` 
Change:
```python
content = "tell application \"iTerm\"\n"
```
To:
```python
content = "tell application \"iTerm 2\"\n"
```

Then try running the `pokemon ****` command again 👍

**Comment by Yzchen1994** [comment]
I changed line 10 of scripter.py to 
`content = "tell application \"iTerm 2\"\n"`

And the line 1 of background.scpt has automatically changed to 
`tell application "iTerm 2"`

But I still got the error 
`/Users/yuzechen/.Pokemon-Terminal/./Scripts/background.scpt:41:48: script error: Expected end of line but found identifier. (-2741)`

**Comment by tommcgurl** [comment]
@Yzchen1994 Another thing you can try is manually clicking the `background.scpt` script. Apple script should open and prompt you to select your iterm2 application from the applications folder. Once you select it it should display the script with the correct name. 

Use the name that it puts in the script to modify the `scripter.py` file. In my case the name was "iTerm 2" but yours may be different?

**Comment by Yzchen1994** [comment]
@tommcgurl It turns out that the name is "iTerm", but changing back to "iTerm" still causes the error `/.Pokemon-Terminal/./Scripts/background.scpt:39:46: script error: Expected end of line but found identifier. (-2741)`

**Comment by tommcgurl** [comment]
@Yzchen1994 Hmm sorry that didn't work. Is the path to your `.Pokemon-Terminal` repo listed in the `background.scpt` file correct?

**Comment by tommcgurl** [comment]
Also does that file work when ran through apple scripts?

**Comment by Yzchen1994** [comment]
@tommcgurl It works now. I changed "iTerm 2" to "iTerm2"

**Comment by tommcgurl** [comment]
Awesome 👍

**Comment by anushavasudev** [comment]
@tommcgurl Yes. That fixed it! Thanks a lot :)
