### ISSUE TITLE
Pokemon aspect ratios match the terminals aspect ratios

### ISSUE THREAD

**Issue by binamkayastha** [LazoCoder/Pokemon-Terminal#151]
I like to make my windows different sizes using spectacle or chunkwm, so the pokemon backgrounds looks uber stretched.

I was wondering if it was possible to keep them the same aspect ratio, by setting the background color, and then setting a fixed aspect ratio background. I'd be willing to work on it but I need some help since I've never worked with osa scripts before.

Thanks!

**Comment by jimmyorourke** [comment]
Sounds like you're talking about mac, so I'd say figure out how to do what you want manually in `iTerm2` and then take a look at https://www.iterm2.com/documentation-scripting.html

**Comment by binamkayastha** [comment]
Thanks for the link! Looks like it's not currently possible with iTerm2 :(
