### ISSUE TITLE
iTerm2 cannot set wallpaper

### ISSUE THREAD

**Issue by StephenGregory** [LazoCoder/Pokemon-Terminal#158]
Iterm2: Build 3.2.4
Pokemon-terminal: 1.1.1
macOS: 10.12.6

Recently updated Iterm2 and Pokemon terminal. Getting the following error when running `pokemon`:

```
71:87: execution error: iTerm got an error: Can’t set current window to "/usr/local/lib/node_modules/pokemon-terminal/pokemonterminal/Images/Generation VI - Kalos/670.jpg". (-10006)
```

Edit: Oh, I see. Version 1.1.1's command is: 
`osascript -e 'tell application "iTerm" to tell current session of current window to set background image to "/usr/local/lib/node_modules/pokemon-terminal/pokemonterminal/Images/Generation II - Johto/208.jpg"'`

Though 1.2.0, which is unpublished, is:

`osascript -e 'tell application "iTerm2" to tell current session of current window to set background image to "/usr/local/lib/node_modules/pokemon-terminal/pokemonterminal/Images/Generation II - Johto/208.jpg"'`

Which works. Can you publish 1.2.0?

**Comment by sylveon** [comment]
I'm assuming you used npm? I don't know who controls the npm package, probably @LazoCoder

**Comment by StephenGregory** [comment]
Correct.

**Comment by LazoCoder** [comment]
Yes, I control the npm package. I'll update it.

**Comment by LazoCoder** [comment]
Updated.
