### ISSUE TITLE
High Resolution

### ISSUE THREAD

**Issue by OptimusV5** [LazoCoder/Pokemon-Terminal#161]
Good job guys!
I wonder if the resolution of pictures could be higher than current 1920 * 1080?
For example 2880 * 1800 or 4K.

**Comment by LazoCoder** [comment]
It's a good idea but unfortunately the artist has disappeared from the face of the earth and I do not have their contact information.

The images are very simple/minimal so in theory it should be possible to convert it to higher resolution with code.
