### ISSUE TITLE
Allow path of Python 3.6 to be selected

### ISSUE THREAD

**Issue by crutchcorn** [LazoCoder/Pokemon-Terminal#163]
I have python 3.6 installed to my system under the `py` package name. This is because I need both python 2 and 3 installed and these are the default ways of aliasing both. I'd love an input to be able to pass a custom path for Python 3.6 in a param

**Comment by jimmyorourke** [comment]
This is on Windows?

**Comment by crutchcorn** [comment]
Yes, sorry, should have included this. I installed via the `npm i -g` command

**Comment by sylveon** [comment]
We have a python 3.6 shebang, so I think just running `py pokemon` would be sufficient

**Comment by jimmyorourke** [comment]
shebang does nothing on windows.
I'm not sure how the npm install works, but with the pip install if you install with pip3 and have your sites in the path, you should just be able to run `pokemon`

**Comment by crutchcorn** [comment]
```
C:\Users\CorbinCrutchley
λ  py "C:\Users\$([Environment]::UserName)\AppData\Roaming\npm\node_modules\pokemon-terminal\pokemon"
This terminal emulator is not supported.
```

**Comment by sylveon** [comment]
As @crutchcorn just demonstrated, a shebang meaning nothing for the operating system doesn't prevents `py` from parsing it. If it where running on Python 2, it wouldn't have went that far.

**Comment by LazoCoder** [comment]
I've updated the npm package, everything should be good now. Reopen the issue if there is still a problem.
