### ISSUE TITLE
Windows 10 conemu shows UnknownOption everytime

### ISSUE THREAD

**Issue by OHR7** [LazoCoder/Pokemon-Terminal#164]
no matter the way I enter a command it shows UnknownOption
![image](https://user-images.githubusercontent.com/9056156/53295404-8dd71b80-37af-11e9-8eef-34dccfbb1cca.png)

**Comment by jimmyorourke** [comment]
when you so to settings from the menu, which version of conemu does it indicate in the top bar?

**Comment by jimmyorourke** [comment]
Basedon https://conemu.github.io/en/Whats_New.html, you will need at least build 171117

**Comment by LazoCoder** [comment]
Did you use npm install? If so, I've updated the package so it should be working properly now.
