### ISSUE TITLE
`pokemon ?` not working

### ISSUE THREAD

**Issue by reznok** [LazoCoder/Pokemon-Terminal#17]
According to the docs, it should be displaying what pokemon is in the terminal. Instead it changes the terminal background (to moltres?) and displays a menu.

**Comment by ZainW** [comment]
I'm using zsh and it just does not do anything,

other commands work fine afaik

**Comment by justinpincar** [comment]
`pokemon \?`

**Comment by sungjaeHong** [comment]
@ZainW i solved that problem
echo PATH="$HOME/.Pokemon-Terminal:${PATH}" >> ~/.zshrc

**Comment by ZainW** [comment]
Justinpincar's solution worked!

the method just uses the last picture loaded and not the actual current image displayed in the terminal

So if you have more than one terminal open it won't necessarily be correct

**Comment by chardskarth** [comment]
Leaving a comment for other pokemon fans and oh-my-zsh users out there. 

Like what @sungjaeHong mentioned, I added the install path to my exported `path` variable in zshrc. So I have the following:  

```
path=($HOME'/.local/bin' $path $HOME'/.local/pipx/venvs/pokemon-terminal')
export path
```
