### ISSUE TITLE
Feh - xprop call

### ISSUE THREAD

**Issue by regenbogencode** [LazoCoder/Pokemon-Terminal#179]
I'm running into an issue when trying to change the wallpaper. The calls take really long/freezes the terminal (see below), while debugging I found out that the cause is the xprop call from the Feh adapter.

In b562a5c89a65cef5a2af8f34deb0b8da5b718fc1 the call gets changed from `xprop -root -notype`
to`xprop root -notype`,
which changes the cursor to an selection cursor and waits for the user to select a window. Therefore the execution of pokemon-terminal is halted until the user clicks a window. Additionally the result of this call is always `root: no such atom on any window.`, instead the properties of the root window.

System:
- Python3.9
- Wayland/Sway

**Comment by sylveon** [comment]
My bad, thanks for the PR.
