### ISSUE TITLE
Feature request: pokemon clear

### ISSUE THREAD

**Issue by justinpincar** [LazoCoder/Pokemon-Terminal#18]
Love it so far and already added to startup script. There are some times when I do need to be professional though, so a `pokemon clear` command to reset the terminal, or at least to set a black/white default, would be really nice.

**Comment by samosaara** [comment]
I bet you mean on iTerm2, but I think it's a great idea regardless and can be easily implemented in the terminology version. I think it's a great idea and I support it...

**Comment by LazoCoder** [comment]
Done. You can now use *pokemon clear* to remove the current pokemon.
