### ISSUE TITLE
Typo in using python re library -- supposed to be lowercase :)

### ISSUE THREAD

**Issue by ProNibs** [LazoCoder/Pokemon-Terminal#189]
https://github.com/LazoCoder/Pokemon-Terminal/blob/154d0354350f50b4867dd6e254ecc0570ac47e51/pokemonterminal/terminal/adapters/windowsterminal.py#L38

**Comment by sylveon** [comment]
It's not - `re.Match` is a type (a match object passed in by `re.sub()`) and `re.match()` is a function.

You can easily see this by typing both in a Python REPL:
![image](https://user-images.githubusercontent.com/6440374/89358752-31f60f00-d692-11ea-938e-a9898d715aa8.png)

**Comment by ProNibs** [comment]
I just installed this locally, and the error I was getting was re.Match() doesn't exist. 
Also, doing locally as you suggested when using Python 3.6.5 does not find that library.
I had to go into the file manually and lowercase it and it started working, so maybe it's just my environment that was having this issue.

**Comment by sylveon** [comment]
Ah, my bad, seems like it was added with Python 3.7: https://github.com/python/cpython/commit/0b5e61ddca73ad4fe597fb15065115b0285c8849

I'll update the requirements to mention Python 3.7

**Comment by ProNibs** [comment]
Cool beans, glad I could help 👍
