### ISSUE TITLE
Error .Pokemon-Terminal/./Scripts/background.scpt

### ISSUE THREAD

**Issue by avatarr** [LazoCoder/Pokemon-Terminal#19]
I got error 
`.Pokemon-Terminal/./Scripts/background.scpt:39:46: script error: Expected end of line but found identifier. (-2741)`

I use with zsh my .zshrc look like this 

<img width="1309" alt="screen shot 2560-06-09 at 2 57 28 pm" src="https://user-images.githubusercontent.com/1640817/26966410-221bed7a-4d24-11e7-8094-7c51485c950c.png">

**Comment by LazoCoder** [comment]
See the solution in #15

**Comment by cclauss** [comment]
@avatarr  Is this issue closed?

**Comment by avatarr** [comment]
I still got error but I will try it again, may be you an close this issues
