### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by aidanharris** [LazoCoder/Pokemon-Terminal#20]
It'd be neat if this had completion support so that you could do something like `pokemon pik` <kbd>TAB</kbd> which would complete to `pokemon pikachu`.

**Comment by LazoCoder** [comment]
Yeah... I wish I knew how to implement this.
But in case you didn't know, the script does actually try to guess the pokemon if you type 3 letters or more. So hitting enter on ```pokemon pik``` actually will change it to pikachu. Likewise if you type ```pokemon dos``` it will change it to gyarados.

**Comment by charlesmilette** [comment]
https://github.com/scop/bash-completion might be a good place to start

**Comment by LazoCoder** [comment]
This is a good suggestion but the internal search should be enough for now.
