### ISSUE TITLE
pokemon terminal not working

### ISSUE THREAD

**Issue by siddht1** [LazoCoder/Pokemon-Terminal#29]
i use linux mint kde,so the console over here is konsole.
when i type commands " pokemon pikachu" over here
"Terminal emulator not supported" is been printed

**Comment by giftig** [comment]
> Make sure you have Terminology

The error message is pretty clear, no? You're not using a supported terminal emulator.

**Comment by siddht1** [comment]
can you tell me which terminals are supported

**Comment by LazoCoder** [comment]
> Supports iTerm2, Terminology & Tilix
