### ISSUE TITLE
Add alias to `pokemon`

### ISSUE THREAD

**Issue by vladyslavstartsev** [LazoCoder/Pokemon-Terminal#35]
I think it will be nice one if we have alias that for `pokemon` that will be called `ichooseyou` so you can `ichooseyou pikachu`. Not my idea, found this on reddit https://www.reddit.com/r/linux/comments/6gs33v/pokemon_terminal_for_macos_linux/

**Comment by LazoCoder** [comment]
I like this idea. I'm gonna add it.

**Comment by vladyslavstartsev** [comment]
Yay!

**Comment by LazoCoder** [comment]
Done.
