### ISSUE TITLE
Database file unnecessary lines?

### ISSUE THREAD

**Issue by hvze** [LazoCoder/Pokemon-Terminal#39]
Looking at the Pokemon database text file, the id's correspond to the line they are on, why bother with the id if it is also the line number?

**Comment by LazoCoder** [comment]
You are right, it's unnecessary. I didn't realize this when I created the file. But removing it would only reduce the project size by a few kilobytes which isn't much in the grand scheme of things.

**Comment by charlesmilette** [comment]
I reduced the size from 70 mb to 26 mb in the AUR package by adding these commands in the packaging process:

      rm .npmignore .gitignore LICENSE package.json
      rm -rf .git/ .idea/ Samples/ Scripts/

So I would assume `Samples` is taking a lot of that space (And I should really remove that `-f`)

**Comment by LazoCoder** [comment]
Awesome

**Comment by cclauss** [comment]
What is the todo of this issue?  Should something be added to the .gitignore file?  Or can this issue be closed?
