### ISSUE TITLE
 Is it supported on zsh?

### ISSUE THREAD

**Issue by YanYuanFE** [LazoCoder/Pokemon-Terminal#40]
os：linux ubuntu16
terminal: on-my-zsh

thanks!

**Comment by charlesmilette** [comment]
It depends of the [terminal emulator](https://en.wikipedia.org/wiki/Terminal_emulator) you're using.

**Comment by theothertom** [comment]
Just tried on Zsh, and yes - it works fine. This isn't using anything bash specific, just that the instructions tell you to put the PATH modification in your bashrc. You can do the same with your zshrc

**Comment by aweimeow** [comment]
I tried Zsh, just replace command as following: 
```bash
echo PATH="$HOME/.Pokemon-Terminal:$"PATH"" >> ~/.zshrc
source ~/.zshrc
```

**Comment by YanYuanFE** [comment]
I have Terminology and open it, input command as following:
`pokemon 130`

invalid???

**Comment by YanYuanFE** [comment]
![_139](https://user-images.githubusercontent.com/17774285/27374759-87a7fbd2-569f-11e7-92eb-1961ad09d69f.png)
As it

**Comment by aweimeow** [comment]
@YanYuanFE 
Maybe your terminal emulator doesn't support it.

I use iTerm2, zsh, and oh-my-zsh: 
![](https://i.imgur.com/DTk1lT1.png)

**Comment by awaisabir** [comment]
Do I have to type `pokemon name` every time I open a new terminal? It doesn't seem to be putting it by default. I am using oh-my-zsh and iTerm.

**Comment by charlesmilette** [comment]
You can add it to your .zshrc:

echo "pokemon pikachu" >> ~/.zshrc

**Comment by charlesmilette** [comment]
@YanYuanFE look at issue #33

**Comment by Danielapariona** [comment]
How can I see the pokemon list?

**Comment by LazoCoder** [comment]
To see all the pokemon in the kanto region:
```pokemon -dr -r kanto -v```
For johto:
```pokemon -dr -r johto -v```
etc...

**Comment by samosaara** [comment]
Just my 2 cents, when I implemented that, I thought it wouldn't make sense a -dr (dry run) without being verbose(-v), so -dr implies -v.

Now I'm not sure anymore about such design decision, can always be changed though.

**Comment by LazoCoder** [comment]
Its ok, no need to change it.
