### ISSUE TITLE
The image can't be displayed as background image in Tilix.

### ISSUE THREAD

**Issue by ZanderChang** [LazoCoder/Pokemon-Terminal#41]
But in preferences it has been set as the background image.

**Comment by pasqenr** [comment]
Hello, I'm new on GitHub and to Tilix but after reading the [Tilix FAQ](https://github.com/gnunn1/tilix/wiki/FAQ) I've fixed adjusting the _Transparency_ in the _Default_ profile.

Hope it helps.

**Comment by LazoCoder** [comment]
I actually had the same issue and adjusting the transparency as per @pasqenr's advice fixed it. I should probably add this to the readme as it seems to be a common problem.

**Comment by Fiskie** [comment]
Since Tilix uses gsettings we could have it probe for the current transparency setting and display a warning.

**Comment by LazoCoder** [comment]
@Fiskie good idea

**Comment by ZanderChang** [comment]
@pasqenr thx,that works for me!
