### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by spinside** [LazoCoder/Pokemon-Terminal#5]
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5: bad interpreter: No such file or directory

**Comment by LazoCoder** [comment]
Open up main.py and in the first line put the location of your python interpreter. The first line looks like this, but it may be wrong according to your system:
``#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5``

If you have python3.6 you might have to change it to this instead:
``#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6``

Alternatively, if you don't want to do that you could just execute main.py like you would any other python script:
``$ python3.5 main.py pikachu``
or
``$ python main.py pikachu``

This should fix your problem for now. I'll have to find out a way for the program to find out automatically where the user has python installed and generate the code dynamically based on the environment.

Thanks for bringing up this issue!

**Comment by LazoCoder** [comment]
This is fixed now so you don't have to make any changes to main.py.

**Comment by spinside** [comment]
Thank you! Updated and it runs like a charm(ander)!

**Comment by LazoCoder** [comment]
LOL no problem
