### ISSUE TITLE
Fish shell on MacOS?

### ISSUE THREAD

**Issue by zyxep** [LazoCoder/Pokemon-Terminal#53]
Anyone got it to work?

**Comment by samosaara** [comment]
AFAIK, this project isn't shell dependent and rather terminal emulator dependent, it should work regardless of shell as long as you have a compatible terminal emulator, are you having any problems? If so post logs and more detailed description.

**Comment by zyxep** [comment]
I figured it out with a little help from Google as always :D

`echo "set -gx PATH \$PATH \$HOME/.Pokemon-Terminal" >> ~/.config/fish/config.fish`

**Comment by samosaara** [comment]
Oh wait. You mean the installation instructions are for bash only. That's a great observation I think it deserves to go to the readme file.

**Comment by zyxep** [comment]
My colors are off though.

**Comment by Vistaus** [comment]
@zyxep Are you sure this works? 'Cause I've tried it with Fish on my laptop (which runs Solus (Linux)) and it doesn't work. It can't find the command 'pokemon'.
