### ISSUE TITLE
[Request] Gnome-Terminal Support

### ISSUE THREAD

**Issue by AbstractClass** [LazoCoder/Pokemon-Terminal#55]
Currently attempting to use command through gnome-terminal just gives "This terminal emulator is not supported."

**Comment by asukaliy1** [comment]
me too, i see it declares that it supports the gnome terminal, however it doesn't work...

**Comment by samosaara** [comment]
Where do we declare we support the Gnome terminal? If it's not clear, we support Gnome the desktop environment to set the wallpaper, not it's terminal, and it's not even our fault, gnome terminal itself doesn't support image backgrounds, we just can't do it.
