### ISSUE TITLE
color scheme?

### ISSUE THREAD

**Issue by zyxep** [LazoCoder/Pokemon-Terminal#62]
I just use default scheme and it looks really bad
any recommendations for text color scheme?

**Comment by LazoCoder** [comment]
Can you post a screenshot?

**Comment by zyxep** [comment]
http://imgur.com/a/ogVBX

when just doing a random one, sometimes the colors are really hard to read

**Comment by LazoCoder** [comment]
I don't know which terminal emulator you are using but if its iTerm2 there is two things you can do:
1. Play around with the blending settings in the profile. You can set the background images to be darker. This will make it easier to read text that has light colors.
2. Turn on the transparency + have darker colored text. As per the suggestions in the readme (see the screenshot of tauros).
