### ISSUE TITLE
Not working on Linux Mint 18.1 using Tilix

### ISSUE THREAD

**Issue by Tiwaz89** [LazoCoder/Pokemon-Terminal#74]
I installed via npm following the documentation. And I'm running python 3.5.2. When I run `pokemon tauros` for example in Tilix, nothing happens. It does indeed recognise the `pokemon` command but running it yields no result.

**Comment by LazoCoder** [comment]
You need to adjust the transparency. See #41

**Comment by Tiwaz89** [comment]
Confirm that adjusting the transparency fixed the issue.

**Comment by LazoCoder** [comment]
Thank you for the confirmation.
