### ISSUE TITLE
Travis continuous integration tests are not running on this repo

### ISSUE THREAD

**Issue by cclauss** [LazoCoder/Pokemon-Terminal#76]
The goal behind https://github.com/LazoCoder/Pokemon-Terminal/pull/60 was to have Travis-CI  automatically run flake8 and pytest tests on every pull request. This will help contributors know if their submissions would break the build. To turn on this free service, @LazoCoder would need to do steps 1 and 2 of https://docs.travis-ci.com/user/getting-started/

**Comment by LazoCoder** [comment]
I'm aware of this. Will do it soon.

**Comment by LazoCoder** [comment]
Travis-CI has been enabled.
