### ISSUE TITLE
Scripter could accept image_file_path instead of pokemon 

### ISSUE THREAD

**Issue by cclauss** [LazoCoder/Pokemon-Terminal#83]
Scripter and the adapter scripts could be generalized to accept image_file_path instead of pokemon objects.
* scripter.change_terminal(pokemon) --> scripter.change_terminal(image_file_path) 
* scripter.change_wallpaper(pokemon) --> scripter.change_wallpaper(image_file_path)
* similar changes in the adapter files

Currently these functions pass around pokemon instances and then at the end the call chain merely do pokemon.get_path().  Changing them to accept file paths and do the pokemon.get_path() higher up the call stack would reduce data movement, ease testing, and make scripter and friends easier to spin out into a separate project which could attract broader developer support for building and testing adapters.

**Comment by LazoCoder** [comment]
Agreed.
