### ISSUE TITLE
extras are printing in lowercase, not Title

### ISSUE THREAD

**Issue by cclauss** [LazoCoder/Pokemon-Terminal#89]
`$ pokemon all`

```
[ ... ]
127 Pinsir          257 Blaziken        387 Turtwig         --- wormadam-trash
[ ... ]
```

**Comment by LazoCoder** [comment]
imo it doesn't matter if extras are printing in lowercase. What if a user adds in a custom image and names it "fh4dk3jsfhsk", should we really change that to "Fh4dk3jsfhsk"?
