### ISSUE TITLE
Holy crap this is awesome!

### ISSUE THREAD

**Issue by ibbatta** [LazoCoder/Pokemon-Terminal#9]
Sorry this is not an issue but I would thank to you for this epic project <3

**Comment by LazoCoder** [comment]
No problem! I'm glad you like it!

**Comment by ibbatta** [comment]
Damn dude, you change my dev life ahahaha
![screen shot 2017-06-07 at 17 19 09](https://user-images.githubusercontent.com/4375285/26886387-7b294c8a-4ba5-11e7-81f7-5189ad8a7dfd.png)

**Comment by LazoCoder** [comment]
ahaha

**Comment by zodman** [comment]
can work with terminator on linux ?

**Comment by LazoCoder** [comment]
@zodman Yes.
