### ISSUE TITLE
Should we stop supporting Python 3.5 and earlier?

### ISSUE THREAD

**Issue by samosaara** [LazoCoder/Pokemon-Terminal#95]
Python 3.6 is the latest stable version of python. From December of 2016 brings many awesome feature like formatted strings, `__init_subclass__` and many other great improvements, naturally since it's a newer version, but users of more 'conservative' distros might not have the version (even though is very safe to assume such distros would have an available upgrade given how popular and important python is noways. What I'm really asking is are you guys O.K increasing the minimum version to python 3.6

**Comment by LazoCoder** [comment]
This is a hard question to answer. Thousands of people are using this application and there's no way to know what percentage of them are still using python 3.5. My worry is that the program will break for them when they try to upgrade to the latest version of Pokemon Terminal and they realize that they also need to upgrade python as well.

My initial impulse was to to say yes, that its okay to use python 3.6 but then I realized that there are a lot of people who use Pokemon Terminal at work. These people may have restricted privileges on their computers and my not be able to upgrade software so easily.

Do you need python 3.6 for the command engine rework?

**Comment by cclauss** [comment]
> And I don't think people are really using pokemon backgrounds on work computers xD

You would be shocked to see what some people do on their work computers ;-)  Corporate IT staff often to not give users the access rights required to change the version of Python installed on their work computers.  Perhaps we would get more feedback if you changed the title of this issue to "**Should we stop supporting Python 3.5 and earlier?**".

**Comment by samosaara** [comment]
Yeah sure, what do I know, but my biggest point is: To people whom already have python 3 already might not be a big deal to upgrade, or most likely, already have python 3.6.

**Comment by samosaara** [comment]
Since there it was no negative feedback, the change has been merged with #94
